name: ➕ Add, Update, or Delete Known Passkey Deployment
title: "Add <service name>"
labels: ["deployments-list"]
description: Add, update, or delete a service in the active deployments list
body:
  - type: dropdown
    id: type
    validations:
      required: true
    attributes:
      label: Type
      description: >-
        Change type
      multiple: true
      options:
        - New service
        - Update existing entry
        - Delete existing entry
  - type: input
    id: service_name
    attributes:
      label: Service Name
      description: ex Best Buy
    validations:
      required: true
  - type: input
    id: service_rp
    attributes:
      label: Service URL
      description: ex bestbuy.com
    validations:
      required: true
  - type: checkboxes
    id: passkeys_web
    attributes:
      label: Web
      description: Service supports signing in with a passkey on web
      options:
        - label: Supported
          required: false
  - type: checkboxes
    id: passkeys_app
    attributes:
      label: "Apps"
      description: Service supports signing in with a passkey in native apps
      options:
        - label: Supported
          required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Notes to display
    validations:
      required: false
  - type: textarea
    id: links
    attributes:
      label: Links
      description: "Links to display (ex: support article)"
    validations:
      required: false
  - type: checkboxes
    id: Contact
    attributes:
      label: "Contact"
      description: Are you a point of contact for this service?
      options:
        - label: I am
          required: false 
