[[main]]
name = "Docs"
url = "/docs/intro/what-are-passkeys/"
# url = "/docs/1.0/prologue/introduction/"
weight = 10

#[[main]]
#name = "FAQs"
#url = "/faq/"
#weight = 20

[[main]]
name = "Device Support"
url = "/device-support/"
weight = 30

[[main]]
name = "About"
url = "/about/"
weight = 90

[[footer]]
name = "about passkeys.dev"
url = "/about/"
weight = 10

[[footer]]
name = "Creative Commons license"
url = "https://passkeys.dev/about/#copyright-and-attributions"
weight = 15